# The 'common' role is used to install Ubuntu operating system software that is
# common to all servers
---
- name: Set hostname
  hostname: name="{{ hostname }}"
  when: hostname is defined

- name: Validate Ansible version
  assert:
    that:
     - "{{ ansible_version is defined }}"
     - "{{ ansible_version.full | version_compare(minimum_ansible_version, '>=') }}"
    msg: "Your Ansible version is too old. Version {{ minimum_ansible_version }} is required. Your version is {{ ansible_version.full | default('< 1.6') }}"

- name: Update Apt
  apt: update_cache=yes

- name: Checking essentials
  apt: name="{{ item }}" state=present update_cache=yes
  with_items:
  - build-essential
  - python-software-properties
  - python-pycurl
  - python-mysqldb
  - curl
  - git-core
  - git
  - make
  - vim
  - nano
  - wget
  - pkg-config
  - unzip
