# Ansible Playbook for Local Workstation
# Used by Vagrant via Ansible Provisioner
---
- name: "Application Server: Setup Local Development Environment"
  hosts: default
  become: true
  # remote_user: vagrant
  # gather_facts: false

  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - homeDir: /home/ubuntu

  roles:
    - { role: common, tags: common }
    # No need for Nginx web server for non web-apps
    # - { role: nginx, tags: nginx }
    - { role: rvm_io.ruby, tags: ruby }
    - { role: app_setup, tags: app_setup }
